import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Destiny 2 Wayfinding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/destiny2_icon.png" />
      </head>
      <body className="font-poppins">{children}</body>
    </html>
  );
}
